name: User story
description: Create a new user story
title: "[Story]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this user story!
        
  - type: input
    id: story-persona
    attributes:
      label: "As a"
      description: "Who are we building this for? We’re not just after a job title, we’re after the persona of the person. Max. Our team should have a shared understanding of who Max is. We’ve hopefully interviewed plenty of Max’s. We understand how that person works, how they think and what they feel. We have empathy for Max."
      placeholder: |
        <persona>,
    validations:
      required: true
  - type: input
    id: story-want
    attributes:
      label: "I want to"
      description: "Here we’re describing their intent — not the features they use. What is it they’re actually trying to achieve? This statement should be implementation free — if you’re describing any part of the UI and not what the user goal is you're missing the point"
      placeholder: |
        <want to>
    validations:
      required: true
  - type: input
    id: story-goal
    attributes:
      label: "So that"
      description: "how does their immediate desire to do something this fit into their bigger picture? What’s the overall benefit they’re trying to achieve? What is the big problem that needs solving?"
      placeholder: |
        <so that>.
    validations:
      required: true
